name: Selenium CI/CD Pipeline

# Run the workflow on every push to any branch and daily at midnight.
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'

      - name: Run Selenium Tests
        run: |
        ./gradlew clean test
